### ISSUE TITLE
Using MusicExamples on OS X

### ISSUE THREAD

**Issue by MikeiLL** [uliska/musicexamples#12]
I have just cloned MusicExamples from github into /usr/local/texlive/texmf-local/tex/latex (OS X).

I am still unable to get:

```
\begin{quote}
\begin{verbatim}
\documentclass{article}
\usepackage{musicexamples}
\begin{document}
Test
\end{document}
\end{verbatim}
\end{quote}
```

to compile.

This is the error:

```
This is TeX, Version 3.14159265 (TeX Live 2014) (preloaded format=tex)
(./text.tex
! Undefined control sequence.
l.1 \begin
```

I ran `texhash` and can compile the following code, which uses the musicexamples package:

```
\documentclass[fontsize=12pt, paper=a4]{scrlttr2}

\usepackage{musicexamples}

% Dont forget to read the KOMA-Script documentation, scrguien.pdf

\setkomavar{fromname}{} % your name
\setkomavar{fromaddress}{Address \\ of \\ Sender}

\setkomavar{signature}{} % printed after the \closing
\renewcommand{\raggedsignature}{\raggedright} % make the signature ragged right

\setkomavar{subject}{} % subject of the letter

\begin{document}
\begin{letter}{Name and \\ Address \\ of \\ Recipient}

\opening{}  % eg. Hello



\closing{} %eg. Regards

\end{letter}
\end{document}
```

I've tried compiling via LaTeX gui as well as just by running `tex file.tex` in the command line. Any suggestions?

**Comment by uliska** [comment]
If the first example you give is really your complete input file it can't compike because you have two environments *outside* of \documentclass.

Remove the first two and last two lines and try again.

**Comment by MikeiLL** [comment]
Hi @uliska. I was able to compile the documentation after installing the [Inconsolata](http://levien.com/type/myfonts/inconsolata.html) font by downloading it from Google and moving into the `~/Library/Fonts` directory on OSX. I'm using a `song.lytex` approach to making the songbook at this point and not totally sure if or how this package will tie in. I would love to see the PDF file that is supposedly linked to from here: http://www.openlilylib.org/public/tutorials/createSongbooks.pdf

**Comment by uliska** [comment]
I've now fixed the broken links issue, and the PDF is available from https://openlilylib.org/public/tutorials/createSongbooks.pdf.

I didn't consider the `lilypond-book` approach when developing `musicexamples`, but actually it *should* work well, as you can simply insert a lilypond-book style score inside the musicexamples commands/environments. They don't really care what's in them.

Please report back if it works, so I know about it.

**Comment by uliska** [comment]
Closing due to lack of followup comments
